--- 

- name: Install Requirements 
  apt: 
    name: "{{item}}"
    state: present 
    update_cache: yes
  with_items:
    - wget

- name: Download docker deb 
  get_url: 
    url: "{{item}}"
    dest: /tmp
    mode: 0700
    validate_certs: no
  with_items:
    - "https://download.docker.com/linux/debian/dists/{{ansible_distribution_release}}/pool/stable/amd64/containerd.io_{{containerd_version}}_amd64.deb"
    - "https://download.docker.com/linux/debian/dists/{{ansible_distribution_release}}/pool/stable/amd64/docker-ce_{{docker_ce_version}}~debian.{{ansible_distribution_major_version}}~{{ansible_distribution_release}}_amd64.deb"
    - "https://download.docker.com/linux/debian/dists/{{ansible_distribution_release}}/pool/stable/amd64/docker-ce-cli_{{docker_ce_cli_version}}~debian.{{ansible_distribution_major_version}}~{{ansible_distribution_release}}_amd64.deb"
  run_once: yes

- name: Install docker deb 
  apt: 
    deb: "{{item}}"
  with_items:
    - /tmp/containerd.io_{{containerd_version}}_amd64.deb
    - /tmp/docker-ce-cli_{{docker_ce_cli_version}}~debian.{{ansible_distribution_major_version}}~{{ansible_distribution_release}}_amd64.deb
    - /tmp/docker-ce_{{docker_ce_version}}~debian.{{ansible_distribution_major_version}}~{{ansible_distribution_release}}_amd64.deb
  register: docker

- name: Install pip3
  apt:
    #update_cache: yes
    name: python3-pip
    state: latest

- name: Install docker for python
  pip:
    name: docker==4.4.4