---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-molecule
    image: debian-ssh:latest
    pre_build_image: true
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
provisioner:
  name: ansible
  log: True
verifier:
  name: ansible
